function clone(obj){
// return obj;
return JSON.parse(JSON.stringify(obj))}function animate(){requestAnimationFrame(animate),TWEEN.update()}function createPathTween(element,start,end,duration){const origin={x:start.x,y:start.y};return new TWEEN.Tween(start).to(end,duration||DURATION.ballSlide).onStart(function(){element.style.opacity=1}).onUpdate(function(){element.style.webkitTransform="translate("+this.x+"px, "+this.y+"px)"}).onComplete(function(){element.style.opacity=0,this.x=origin.x,this.y=origin.y})}function createLightenTween(element,start,end,duration){return new TWEEN.Tween({opacity:start}).to({opacity:end},duration).onUpdate(function(){
// console.log(this);
element.style.opacity=this.opacity})}function createTurnOnTween(element){return createLightenTween(element,0,1,DURATION.turnOn)}function createTurnOffTween(element){return createLightenTween(element,1,0,DURATION.turnOff)}const POINTS=[
// {x: 232, y: 226},
{x:440,y:120},{x:[580,742],y:[40,130]},{x:940,y:226},{x:[1094,1240],y:[312,230]},{x:1402,y:222},{x:[1576,1320],y:[312,456]},{x:1142,y:566},{x:[988,810],y:[648,554]},{x:646,y:450},{x:[488,320],y:[362,456]},{x:138,y:454},{x:[-26,232],y:[362,226]}],DURATION={ballSlide:1500,turnOn:1e3,turnOff:1e3,enlarge:1e3,slideInText:1e3,slideOutText:1e3};var ball=document.getElementById("ball"),light1=document.getElementById("light1"),light2=document.getElementById("light2"),light3=document.getElementById("light3"),light4=document.getElementById("light4"),light5=document.getElementById("light5"),light6=document.getElementById("light6"),detail=document.getElementById("detail"),stepBg1=document.getElementById("step1-bg"),stepIntro1=document.getElementById("step1-intro"),tweenPath1=createPathTween(ball,clone(POINTS[0]),clone(POINTS[1])),tweenTurnOffLight1=createTurnOffTween(light1),tweenTurnOnLight2=createTurnOnTween(light2),tweenPath2=createPathTween(ball,clone(POINTS[2]),clone(POINTS[3])),tweenTurnOffLight2=createTurnOffTween(light2),tweenTurnOnLight3=createTurnOnTween(light3),tweenPath3=createPathTween(ball,clone(POINTS[4]),clone(POINTS[5])),tweenTurnOffLight3=createTurnOffTween(light3),tweenTurnOnLight4=createTurnOnTween(light4),tweenPath4=createPathTween(ball,clone(POINTS[6]),clone(POINTS[7])),tweenTurnOffLight4=createTurnOffTween(light4),tweenTurnOnLight5=createTurnOnTween(light5),tweenPath5=createPathTween(ball,clone(POINTS[8]),clone(POINTS[9])),tweenTurnOffLight5=createTurnOffTween(light5),tweenTurnOnLight6=createTurnOnTween(light6),tweenPath6=createPathTween(ball,clone(POINTS[10]),clone(POINTS[11])),tweenTurnOffLight6=createTurnOffTween(light6),tweenTurnOnLight1=createTurnOnTween(light1),tweenDetailBg=new TWEEN.Tween({x:0,opacity:.8}).to({x:1,opacity:1},1e3).onUpdate(function(){detail.style.opacity=this.opacity,detail.style.webkitTransform="scale("+this.x+", "+this.x+")"}),tweenShowStepIntro1=new TWEEN.Tween({x:-100}).to({x:100},1e3).onUpdate(function(){stepIntro1.style.webkitTransform="translateX("+this.x+"px)"}),tweenHideStepBg1=new TWEEN.Tween({x:0}).to({x:-2e3},600).delay(3e3).onUpdate(function(){stepBg1.style.webkitTransform="translateX("+this.x+"px)"}),tweenHideStepIntro1=new TWEEN.Tween({x:100}).to({x:-1e3},400).delay(3300).onUpdate(function(){stepIntro1.style.webkitTransform="translateX("+this.x+"px)"}),tweenHideDetailBg=new TWEEN.Tween({x:1,opacity:1}).to({x:0,opacity:.8},1e3).onUpdate(function(){detail.style.opacity=this.opacity,detail.style.webkitTransform="scale("+this.x+", "+this.x+")"});
//endregion
tweenPath1.chain(tweenTurnOffLight1,tweenTurnOnLight2),tweenTurnOnLight2.chain(tweenPath2),tweenPath2.chain(tweenTurnOffLight2,tweenTurnOnLight3),tweenTurnOnLight3.chain(tweenPath3),tweenPath3.chain(tweenTurnOffLight3,tweenTurnOnLight4),tweenTurnOnLight4.chain(tweenPath4),tweenPath4.chain(tweenTurnOffLight4,tweenTurnOnLight5),tweenTurnOnLight5.chain(tweenPath5),tweenPath5.chain(tweenTurnOffLight5,tweenTurnOnLight6),tweenTurnOnLight6.chain(tweenPath6),tweenPath6.chain(tweenTurnOffLight6,tweenTurnOnLight1),tweenTurnOnLight1.chain(tweenPath1),
// tweenPath1.chain(tweenLighten1);
// tweenLighten1.chain(tweenPath2);
// tweenPath2.chain(tweenDetailBg);
// tweenDetailBg.chain(tweenShowStepIntro1);
// tweenShowStepIntro1.chain(tweenHideStepBg1, tweenHideStepIntro1);
tweenPath1.start(),animate();
/*! TechnologyStrength 最后修改于： 2017-09-30 */